export const routes = {
  home: '/',
  discover: '/discover',
  academies: '/academies',
  academyDetail: (slug: string) => `/academies/${slug}`,
  coaches: '/coaches',
  coachDetail: (slug: string) => `/coaches/${slug}`,
  sports: '/sports',
  sportDetail: (slug: string) => `/sports/${slug}`,
  compare: '/compare',
  shortlist: '/shortlist',
  enquiry: (type: 'academy' | 'coach', id: string) => `/enquiry/${type}/${id}`,
  enquirySuccess: '/enquiry/success',
  login: '/login',
  register: '/register',
  onboardingRole: '/onboarding/role',
  forgotPassword: '/forgot-password',
  profile: '/profile',
  profilePersonal: '/profile/personal',
  profileChildren: '/profile/children',
  profilePreferences: '/profile/preferences',
  profileSaved: '/profile/saved',
  profileEnquiries: '/profile/enquiries',
  profileSettings: '/profile/settings',
  admin: '/admin',
} as const;
